### ISSUE TITLE
Does not seem to be rendering sound

### ISSUE THREAD

**Issue by ksdavidc** [zakkolar/scratch-project-viewer#16]
Does not seem to be rendering sound

https://scratch.mit.edu/projects/541322476
https://scratch-viewer.zak.io/view/#project=https://scratch.mit.edu/projects/541698128

**Comment by ksdavidc** [comment]
I realize more specifically it does not render text to speech....

when gf clicked
text2speech_setVoice
forever 
text2speech_speakAndWait
end

**Comment by zakkolar** [comment]
Sorry I missed this sooner!

This seems to be an issue with [Forkphorus](https://github.com/forkphorus/forkphorus), which is what this project uses to render the projects. I'd recommend opening an issue on that project. If it's addressed there, I can pull it into this project!
