### ISSUE TITLE
Please update your version of forkphorus

### ISSUE THREAD

**Issue by GarboMuffin** [zakkolar/scratch-project-viewer#25]
The Scratch API has changed so the version of forkphorus you currently use is unable to load *any* projects. The latest version of forkphorus has been updated to be able to load shared projects. Unshared projects can no longer be loaded. (more information: https://docs.turbowarp.org/unshared-projects)

Your site is causing us to receive a fair amount of invalid issues that we can't do anything about but still spam our inbox:

 - https://github.com/forkphorus/forkphorus/issues/534
 - https://github.com/forkphorus/forkphorus/issues/533
 - https://github.com/forkphorus/forkphorus/issues/535
 - https://github.com/forkphorus/forkphorus/issues/537

We ask that you either update your version of forkphorus or turn off the website as it is currently completely broken and is just misleading users.

**Comment by zakkolar** [comment]
Sorry about that! I just updated with a depreciated message and removed all links to your issues page. The update should be live on the site shortly.
